# Generated by Django 3.2.7 on 2021-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200, null=True)),
                ('StudentId', models.CharField(max_length=50, null=True)),
                ('LecturesAttended', models.IntegerField(null=True)),
                ('TotalLectures', models.IntegerField(null=True)),
            ],
        ),
    ]
